apiVersion: platformapi.kubeplus/v1alpha1
kind: Greeting
metadata:
  name: greetings2
spec:
  REPLICAS: 1
  GREETING: "This is greeting2"
  NODE_PORT: 32761
  IMAGE: "gcr.io/cloud-a4-project/jkm3488-assignment4:latest"
  



