apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeplus-saas-provider
  namespace: default
rules:
- apiGroups:
  - '*'
  - ''
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - workflows.kubeplus
  resources:
  - resourcecompositions
  - resourcemonitors
  - resourcepolicies
  - resourceevents
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - ''
  resources:
  - pods/portforward
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - platformapi.kubeplus
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  - serviceaccounts
  - configmaps
  - events
  - persistentvolumeclaims
  - serviceaccounts/token
  - services
  - services/proxy
  - endpoints
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - ''
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ''
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - pods/eviction
  - replicationcontrollers
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - patch
  - deletecollection
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - delete
  - update
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  - kubernetes.io/kubelet-serving
  - kubernetes.io/kube-apiserver-client
  - cloudark.io/kubeplus
  resources:
  - signers
  verbs:
  - get
  - create
  - delete
  - update
  - patch
  - approve
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - create
  - delete
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  - ingresses
  - networkpolicies
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
